const DOWNLOAD_TORRENT_ROUTE = '/download';

const DELETE_TORRENT_ROUTE = '/delete';

const DELETE_TORRENT_AND_FILES_ROUTE = '/delete-all';

const PAUSE_TORRENT = '/pause';

const CREATE_TORRENT = '/create';

module.exports = {
  DOWNLOAD_TORRENT_ROUTE,
  DELETE_TORRENT_ROUTE,
  DELETE_TORRENT_AND_FILES_ROUTE,
  PAUSE_TORRENT,
  CREATE_TORRENT,
};
