const DOWNLOAD_TORRENT_ROUTE = '/download';

const GET_INFO_TORRENT_ROUTE = '/info';

const DELETE_TORRENT_ROUTE = '/delete';

const DELETE_TORRENT_AND_FILES_ROUTE = '/delete-all';

const PAUSE_TORRENT = '/pause';

module.exports = {
  DOWNLOAD_TORRENT_ROUTE,
  GET_INFO_TORRENT_ROUTE,
  DELETE_TORRENT_ROUTE,
  DELETE_TORRENT_AND_FILES_ROUTE,
  PAUSE_TORRENT,
};
